# Site settings
title: plog
description: > # this means to ignore newlines until the next unindent 
  Code, biology, etc. Hope you enjoy :)

url: "http://plog.logston.me" # the base hostname & protocol for your site
twitter_username: paullogston
github_username:  logston
permalink:        /:title/

